const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
function load(relative){const filename=path.resolve(__dirname,'..',relative);const mod=new Module(filename,module);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));const normal=mod.require.bind(mod);mod.require=id=>id.startsWith('@/')?load(id.slice(2)+'.ts'):id==='./local-data'?load('lib/local-data.ts'):normal(id);mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);return mod.exports;}
const local=load('lib/local-data.ts');const {calculateBazi}=load('lib/bazi.ts');
assert.equal(local.validBirthday('2023-02-29','12:00'),false);assert.equal(local.validBirthday('2024-02-29','12:00'),true);assert.equal(local.validBirthday('2024-01-01','24:00'),false);assert.equal(local.validBirthday('1899-01-01','12:00'),false);assert.equal(local.validBirthday('2100-01-01','12:00'),false);
assert.deepEqual(calculateBazi('2005-12-23','08:37').pillars.map(p=>p.ganZhi),['乙酉','戊子','辛巳','壬辰']);
assert.equal(calculateBazi('2005-12-23','08:37').elements.reduce((n,e)=>n+e.count,0),8);
assert.equal(calculateBazi('2005-12-23','23:30').pillars[2].ganZhi,calculateBazi('2005-12-23','22:30').pillars[2].ganZhi);
assert.notEqual(calculateBazi('2005-12-24','00:30').pillars[2].ganZhi,calculateBazi('2005-12-23','23:30').pillars[2].ganZhi);
const backup={version:1,exportedAt:new Date().toISOString(),readings:[],profiles:[{id:'p',name:'自己',birthday:'2005-12-23',time:'08:37',note:''}],chats:[],settings:{nickname:'云'}};local.validateBackup(backup);assert.throws(()=>local.validateBackup({...backup,profiles:[...backup.profiles,...backup.profiles]}));assert.throws(()=>local.validateBackup({...backup,profiles:[{...backup.profiles[0],birthday:'2023-02-29'}]}));assert.throws(()=>local.validateBackup({...backup,settings:{nickname:'x'.repeat(31)}}));
const store=new Map();global.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};global.sessionStorage={removeItem:()=>{}};local.restoreBackup(backup);assert.equal(local.exportBackup().profiles[0].name,'自己');const before=local.exportBackup();let writes=0;global.localStorage.setItem=(k,v)=>{if(++writes===2)throw new Error('quota');store.set(k,v)};assert.throws(()=>local.restoreBackup({...backup,settings:{nickname:'changed'}}));assert.deepEqual(local.exportBackup().settings,before.settings);
const {NextRequest}=require('next/server');const {POST}=load('app/api/chat/route.ts');const request=messages=>new NextRequest('https://site.example/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages})});
(async()=>{assert.equal((await POST(request([{role:'system',content:'bad'}]))).status,400);assert.equal((await POST(request([{role:'user',content:'x'.repeat(1001)}]))).status,400);delete process.env.LLM_API_KEY;assert.equal((await POST(request([{role:'user',content:'你好'}]))).status,503);process.env.LLM_API_KEY='mock-key';process.env.LLM_BASE_URL='https://model.example';process.env.LLM_MODEL='mock';global.fetch=async(url,opts)=>{const sent=JSON.parse(opts.body);assert.equal(sent.messages[0].role,'system');assert.equal(sent.messages.length,4);return Response.json({choices:[{message:{content:'模拟回复'},finish_reason:'stop'}]})};const response=await POST(request([{role:'user',content:'你好'},{role:'assistant',content:'你好呀'},{role:'user',content:'继续聊聊'}]));assert.equal(response.status,200);assert.equal((await response.json()).text,'模拟回复');console.log('PASS: Bazi fixture, leap days, date bounds, midnight convention, backup validation/rollback, chat validation and model payload.');})().catch(e=>{console.error(e);process.exit(1)});
