'use client';
import { useEffect, useState } from 'react';
import { Cloud, LogIn, LogOut, Mail, ShieldCheck, UserPlus } from 'lucide-react';
import { exportBackup,restoreBackup,validateBackup,type Backup } from '@/lib/local-data';
type User={id:string;email?:string};
type Mode='login'|'signup'|'reset'|'update-password';
type Vault={payload:Backup;revision:number;updated_at:string};
export default function AccountPanel(){
 const [user,setUser]=useState<User|null>(null);const [configured,setConfigured]=useState<boolean|null>(null);const [mode,setMode]=useState<Mode>('login');
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [vault,setVault]=useState<Vault|null>(null);const [cloudLoaded,setCloudLoaded]=useState(false);const [cloudAction,setCloudAction]=useState<'upload'|'restore'|null>(null);
 async function session(){const r=await fetch('/api/auth',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'账户服务不可用。');setConfigured(data.configured);setUser(data.user);return data.user as User|null;}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('mode')==='update-password')setMode('update-password');if(params.has('error'))setError('验证链接无效或已过期。请在发起操作的同一浏览器重新申请邮件并打开。');if(params.has('confirmed'))setMessage('邮箱验证成功。');session().catch(e=>setError(e.message));},[]);
 function changeMode(next:Mode){setMode(next);setPassword('');setConfirmPassword('');setError('');setMessage('');}
 async function auth(action:Mode|'logout'){
  if(busy)return;if((action==='signup'||action==='update-password')&&password!==confirmPassword){setError('两次输入的密码不一致。');return;}
  setBusy(true);setError('');setMessage('');
  try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:email.trim(),password})});const data=await r.json();if(!r.ok)throw Error(data.error||'账户操作未完成。');setPassword('');setConfirmPassword('');setVault(null);setCloudLoaded(false);setCloudAction(null);await session();window.dispatchEvent(new Event('yunjian-auth'));if(action==='logout'){setMode('login');setMessage('已退出。本机资料仍保留，公共设备上请到“我的云笺”清空。');}else if(action==='login'){setMessage('登录成功，可将本机资料保存到云端。');}else if(action==='signup'&&data.signedIn){setMessage('注册成功，已登录。');}else{setMessage(data.message||'操作成功。');if(action==='update-password')setMode('login');}}
  catch(e){setError(e instanceof Error?e.message:'连接失败，请重试。');}finally{setBusy(false);}
 }
 async function readCloud(){setBusy(true);setError('');setMessage('');setCloudAction(null);try{const r=await fetch('/api/cloud',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'云端读取失败。');if(data.ownerId!==user?.id)throw Error('登录账户已变化，请刷新页面后重试。');if(data.vault){validateBackup(data.vault.payload);if(!Number.isSafeInteger(data.vault.revision))throw Error('云端版本信息无效。');}setVault(data.vault);setCloudLoaded(true);}catch(e){setCloudLoaded(false);setError(e instanceof Error?e.message:'云端读取失败。');}finally{setBusy(false);}}
 async function applyCloud(){if(busy||!cloudLoaded)return;setBusy(true);setError('');setMessage('');try{if(cloudAction==='upload'){const payload=exportBackup();const body=JSON.stringify({payload,revision:vault?.revision||0,ownerId:user?.id});if(new Blob([body]).size>3*1024*1024)throw Error('本机资料超过3MB，请先导出备份并精简聊天记录。');const r=await fetch('/api/cloud',{method:'PUT',headers:{'Content-Type':'application/json'},body});const data=await r.json();if(!r.ok){if(r.status===409)setCloudLoaded(false);throw Error(data.error||'云端保存失败。');}setVault({payload,revision:data.revision,updated_at:new Date().toISOString()});setMessage('已保存到当前账户的云端资料。');}else if(cloudAction==='restore'&&vault){restoreBackup(vault.payload);window.dispatchEvent(new Event('yunjian-settings'));setMessage('云端资料已恢复到本机。');}setCloudAction(null);}catch(e){setError(e instanceof Error?e.message:'操作失败。');}finally{setBusy(false);}}
 return <div className="feature-stack"><section className="panel feature-panel account-panel"><div className="section-top"><h2><ShieldCheck size={21}/> 云笺账户</h2><span className="tag">邮箱账户</span></div><p className="muted feature-intro">登录后可保存云端资料，在其他设备登录同一账户后恢复。</p>{configured===null&&!error&&<p role="status">正在检查账户服务……</p>}{configured===false&&<p className="setup-note">账户服务尚未连接。管理员需创建 Supabase 项目、执行建表脚本并配置环境变量；本地起卦和档案仍可使用。</p>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success-note">{message}</p>}
 {user&&<div className="signed-in"><Mail size={19}/><span><small>当前登录</small><b>{user.email||'云笺用户'}</b></span><button className="secondary" disabled={busy} onClick={()=>auth('logout')}><LogOut size={15}/> 退出登录</button></div>}
 {user&&mode!=='update-password'&&<button className="secondary" onClick={()=>changeMode('update-password')}>修改密码</button>}
 {(!user||mode==='update-password')&&<><div className="account-tabs" role="group" aria-label="账户操作">{!user&&<><button type="button" className={mode==='login'?'selected':''} disabled={busy} onClick={()=>changeMode('login')}>登录</button><button type="button" className={mode==='signup'?'selected':''} disabled={busy} onClick={()=>changeMode('signup')}>注册</button></>}</div><h3 className="feature-subtitle">{{login:'欢迎回来',signup:'写下你的第一张云笺',reset:'找回密码','update-password':'设置新密码'}[mode]}</h3><form className="feature-form" onSubmit={e=>{e.preventDefault();auth(mode);}}>{mode!=='update-password'&&<label>邮箱<input type="email" aria-label="账户邮箱" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" disabled={busy}/></label>}{mode!=='reset'&&<label>{mode==='update-password'?'新密码':'密码'}<input aria-label="账户密码" type="password" required minLength={mode==='login'?1:8} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><small className="muted">{mode==='login'?'请输入注册时设置的密码。':'至少8位，建议结合字母、数字和符号。'}</small></label>}{(mode==='signup'||mode==='update-password')&&<label>确认密码<input aria-label="确认账户密码" type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} disabled={busy}/></label>}<button className="primary" disabled={busy||configured!==true}>{mode==='signup'?<UserPlus size={16}/>:<LogIn size={16}/>} {busy?'请稍候…':{login:'登录账户',signup:'创建账户',reset:'发送重置邮件','update-password':'保存新密码'}[mode]}</button></form>{mode==='login'&&<button className="account-forgot" disabled={busy} onClick={()=>changeMode('reset')}>忘记密码？</button>}{mode==='update-password'&&user&&<button className="account-forgot" onClick={()=>changeMode('login')}>取消修改</button>}<p className="muted feature-intro">密码由 Supabase Auth 管理，不写入网站业务数据库或本地备份。验证邮件请在发起注册或重置操作的同一浏览器打开。</p></>}
 </section>{user&&<section className="panel feature-panel"><div className="section-top"><h2><Cloud size={21}/> 我的云端资料</h2><span className="tag">按账户隔离</span></div><p className="muted feature-intro">本机资料和账户云端资料分开保存，不会自动上传或替换。切换账户后，本机资料仍在；保存前请确认资料属于当前账户。</p><button className="secondary" disabled={busy} onClick={readCloud}>{cloudLoaded?'刷新云端状态':'读取云端状态'}</button>{cloudLoaded&&<><p className="muted feature-intro">{vault?`版本 ${vault.revision} · ${new Date(vault.updated_at).toLocaleString('zh-CN')} · ${vault.payload.readings.length}条提问 / ${vault.payload.profiles.length}份档案 / ${vault.payload.chats.length}段聊天`:'当前账户还没有云端资料。'}</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setCloudAction('upload')}>将本机资料保存到云端</button><button className="secondary" disabled={busy||!vault} onClick={()=>setCloudAction('restore')}>从云端恢复到本机</button></div></>}{cloudAction&&cloudLoaded&&<div className="confirm-box"><p>{cloudAction==='upload'?`确认将本机提问、档案、聊天和称呼上传至 ${user.email||'当前账户'}？这将替换该账户原有的云端资料。`:'确认用云端资料替换本机现有资料？建议先到“我的云笺”导出备份。'}</p><div className="button-row"><button className="primary" disabled={busy} onClick={applyCloud}>{busy?'处理中…':'确认'+(cloudAction==='upload'?'保存到云端':'恢复到本机')}</button><button className="secondary" disabled={busy} onClick={()=>setCloudAction(null)}>取消</button></div></div>}</section>}</div>;
}
