'use client';
import { useEffect, useRef, useState } from 'react';
import { MessageCircle, Plus, Send, Trash2, Download } from 'lucide-react';
import { KEYS,loadList,isChat,saveList,downloadFile,type Chat,type ChatMessage } from '@/lib/local-data';
export default function ChatPanel(){
 const [chats,setChats]=useState<Chat[]>([]);const [id,setId]=useState('');const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [confirm,setConfirm]=useState(false);const abort=useRef<AbortController|null>(null);const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{const list=loadList(KEYS.chats,isChat);setChats(list);setId(list[0]?.id||'');setReady(true);}catch{setError('无法读取对话，请检查浏览器存储权限。');}return()=>abort.current?.abort();},[]);
 const active=chats.find(c=>c.id===id);const messages=active?.messages||[];const pending=messages.at(-1)?.role==='user';
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'});},[messages.length,busy]);
 async function send(retry=false){if(abort.current||!ready)return;const text=input.trim();if(!retry&&(!text||text.length>1000))return;if(!retry&&messages.length>=100){setError('这段对话已达到50轮，请开启新对话。');return;}const nextMessages:ChatMessage[]=retry?[...messages]:[...messages,{role:'user',content:text}];if(!nextMessages.length)return;
 const item:Chat={id:active?.id||crypto.randomUUID(),title:active?.title||text.slice(0,25),updatedAt:new Date().toISOString(),messages:nextMessages};const next=[item,...chats.filter(c=>c.id!==item.id)].slice(0,30);
 try{saveList(KEYS.chats,next);}catch{setError('无法保存消息，请检查浏览器存储空间后重试。');return;}
 setChats(next);setId(item.id);setInput('');setError('');setBusy(true);const controller=new AbortController();abort.current=controller;
 try{const result=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:nextMessages.slice(-13)}),signal:controller.signal});const data=await result.json();if(!result.ok)throw new Error(data.error||'暂时无法回复。');if(typeof data.text!=='string'||!data.text.trim()||data.text.length>12000)throw new Error('回复格式异常，请重试。');const completed={...item,messages:[...nextMessages,{role:'assistant' as const,content:data.text}]};const saved=[completed,...next.filter(c=>c.id!==item.id)];setChats(saved);try{saveList(KEYS.chats,saved);}catch{setError('回复已生成，但未能保存。请导出对话后再离开。');}}
 catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'发送失败，请重试。');}
 finally{abort.current=null;setBusy(false);}
 }
 function remove(){if(!active||busy)return;const next=chats.filter(c=>c.id!==id);try{saveList(KEYS.chats,next);setChats(next);setId(next[0]?.id||'');setConfirm(false);setError('');}catch{setError('删除失败。');}}
 return <section className="panel feature-panel chat-panel"><div className="section-top"><h2><MessageCircle size={20}/> 心事聊天</h2><button className="secondary" disabled={busy||!ready} onClick={()=>{setId('');setInput('');setError('');setConfirm(false);}}><Plus size={14}/> 新对话</button></div><p className="muted feature-intro">AI 陪你整理思绪。发送时最近6轮对话会交给本站配置的模型；请勿填写敏感个人信息。</p><div className="chat-toolbar"><select aria-label="选择历史对话" value={id} disabled={busy} onChange={e=>{setId(e.target.value);setInput('');setError('');setConfirm(false);}}><option value="">新的心事</option>{chats.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{active&&<><button className="icon-button" aria-label="导出当前对话" onClick={()=>downloadFile('云笺对话.txt',active.messages.map(m=>(m.role==='user'?'我':'云笺 AI')+'：\n'+m.content).join('\n\n'),'text/plain;charset=utf-8')}><Download size={17}/></button><button className="icon-button" aria-label="删除当前对话" disabled={busy} onClick={()=>setConfirm(true)}><Trash2 size={17}/></button></>}</div>
 {confirm&&<div className="confirm-box"><p>删除当前对话？</p><div className="button-row"><button className="primary" onClick={remove}>确认删除对话</button><button className="secondary" onClick={()=>setConfirm(false)}>取消</button></div></div>}
 <div className="chat-messages" aria-live="polite">{!messages.length&&<div className="chat-empty"><span className="brand-mark">笺</span><h3>今天，有什么想说的？</h3><p>一段心事，一个选择，或只是想找个地方说说话。</p><div className="chat-prompts">{['最近有些迷茫，想理一理方向。','我总是担心别人的看法。','如何把一个大目标变成小行动？'].map(q=><button key={q} onClick={()=>setInput(q)}>{q}</button>)}</div></div>}{messages.map((m,i)=><article className={'chat-bubble '+m.role} key={i}><small>{m.role==='user'?'我':'云笺 · AI'}</small><p>{m.content}</p></article>)}{busy&&<p className="muted" role="status">云笺正在整理思绪……</p>}<div ref={bottom}/></div>
 {error&&<p className="error" role="alert">{error}</p>}{pending&&!busy&&<div className="button-row"><button className="secondary" onClick={()=>send(true)}>重试上一条消息</button><span className="muted">上一条尚未收到回复。</span></div>}
 <form className="chat-compose" onSubmit={e=>{e.preventDefault();send();}}><label className="sr-only" htmlFor="chat-input">聊天内容</label><textarea id="chat-input" placeholder={pending?'上一条消息待回复，可重试或开启新对话':'写下此刻的心事…'} maxLength={1000} rows={3} value={input} disabled={busy||pending||!ready} onChange={e=>setInput(e.target.value)}/><div><small>{input.length} / 1000 · 最近30段对话保存在本机</small><button className="primary" disabled={busy||pending||!input.trim()||!ready}><Send size={15}/> 发送</button></div></form></section>;
}
