'use client';
import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Plus, Pencil, Trash2 } from 'lucide-react';
import { KEYS, isProfile, loadList, saveList, type Profile, validBirthday } from '@/lib/local-data';
import { calculateBazi } from '@/lib/bazi';
const blank={name:'',birthday:'',time:'12:00',note:''};
export default function ProfilesPanel(){
 const [profiles,setProfiles]=useState<Profile[]>([]);const [selected,setSelected]=useState('');const [editing,setEditing]=useState<string|null>(null);const [form,setForm]=useState(blank);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const [deleting,setDeleting]=useState('');
 useEffect(()=>{try{const list=loadList(KEYS.profiles,isProfile);setProfiles(list);setSelected(list[0]?.id||'');setLoaded(true);}catch{setError('无法读取档案，请检查浏览器存储权限。');}},[]);
 const profile=profiles.find(p=>p.id===selected);const chart=useMemo(()=>profile?calculateBazi(profile.birthday,profile.time):null,[profile]);
 function save(e:React.FormEvent){e.preventDefault();setError('');if(!form.name.trim()||!validBirthday(form.birthday,form.time)){setError('请填写称呼、有效的公历出生日期和北京时间，日期不能晚于现在。');return;}if(!editing&&profiles.length>=50){setError('最多保存50份档案，请先删除不需要的档案。');return;}const item={...form,name:form.name.trim(),id:editing||crypto.randomUUID()};const list=editing?profiles.map(p=>p.id===editing?item:p):[item,...profiles];try{saveList(KEYS.profiles,list);setProfiles(list);setSelected(item.id);setEditing(null);setForm(blank);}catch{setError('档案保存失败，请检查浏览器存储空间。');}}
 function remove(){const next=profiles.filter(p=>p.id!==deleting);try{saveList(KEYS.profiles,next);setProfiles(next);if(selected===deleting)setSelected(next[0]?.id||'');if(editing===deleting){setEditing(null);setForm(blank);}setDeleting('');}catch{setError('删除失败，原档案仍保留。');}}
 return <div className="feature-stack"><section className="panel feature-panel"><div className="section-top"><h2><BookOpen size={20}/> 八字档案</h2><span className="tag">{profiles.length} / 50 份</span></div><p className="muted feature-intro">为自己或家人留一份档案。出生资料只保存在当前浏览器，不发送给大模型。</p>{error&&<p role="alert" className="error">{error}</p>}
 <form className="feature-form" onSubmit={save}><div className="form-grid"><label>称呼<input aria-label="档案称呼" maxLength={30} required placeholder="例如：自己" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>公历出生日期<input aria-label="公历出生日期" type="date" min="1900-01-01" max="2100-12-31" required value={form.birthday} onChange={e=>setForm({...form,birthday:e.target.value})}/></label><label>出生时间 · 北京时间<input aria-label="出生时间" type="time" required value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label></div><label>备注 · 可选<textarea aria-label="档案备注" maxLength={300} rows={2} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="记录与这份档案有关的小事"/></label><div className="button-row"><button className="primary" disabled={!loaded}><Plus size={16}/>{editing?'保存修改':'保存并排盘'}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(blank);}}>取消编辑</button>}</div></form>
 {profiles.length>0&&<div className="profile-list">{profiles.map(p=><article className={'profile-item '+(selected===p.id?'selected':'')} key={p.id}><button className="profile-select" onClick={()=>setSelected(p.id)}><b>{p.name}</b><small>{p.birthday} · {p.time}</small></button><button className="icon-button" aria-label={'编辑档案：'+p.name} onClick={()=>{setEditing(p.id);setForm(p);}}><Pencil size={16}/></button><button className="icon-button" aria-label={'删除档案：'+p.name} onClick={()=>setDeleting(p.id)}><Trash2 size={16}/></button></article>)}</div>}
 {deleting&&<div className="confirm-box" role="alert"><p>确定删除这份档案吗？此操作不可撤销。</p><div className="button-row"><button className="primary" onClick={remove}>确认删除档案</button><button className="secondary" onClick={()=>setDeleting('')}>取消</button></div></div>}</section>
 {profile&&chart?<section className="panel feature-panel"><div className="section-top"><h2>{profile.name}的四柱</h2><span className="tag">日主 · {chart.dayMaster}</span></div><p className="muted feature-intro">{chart.lunar}</p><div className="pillar-grid">{chart.pillars.map(p=><div className="pillar" key={p.label}><small>{p.label}</small><strong>{p.ganZhi}</strong><span>{p.elements}</span><small>{p.god}</small><small>{p.nayin}</small></div>)}</div><h3 className="feature-subtitle">五行字数</h3><div className="elements">{chart.elements.map(e=><div key={e.name}><span>{e.name}</span><div><i style={{width:`${e.count/8*100}%`}}/></div><b>{e.count}</b></div>)}</div><p className="muted">统计四柱八个字对应的五行数量，不等于五行旺衰、喜用神或命运评分。</p>{profile.note&&<p className="profile-note">{profile.note}</p>}<details className="method-note"><summary>排盘规则与时间说明</summary><p>采用 lunar-typescript 历法库，以北京时间（UTC+8）输入公历日期；年柱按立春、月柱按节气划分，日柱按零点换日（sect=2）。未校正真太阳时、出生地经度或历史夏令时；不确定出生时间时请勿把默认12:00视为真实时柱。暂不计算大运、流年或喜用神。</p></details></section>:<section className="panel empty"><BookOpen size={36}/><h3>写下第一份档案</h3><p>保存出生信息后，即可查看四柱与五行分布。</p></section>}</div>;
}
