'use client';
import { useEffect, useRef, useState } from 'react';
import { Download, Upload, UserRound } from 'lucide-react';
import { KEYS,exportBackup,validateBackup,restoreBackup,downloadFile,type Backup } from '@/lib/local-data';
export default function SettingsPanel(){
 const [nickname,setNickname]=useState('');const [counts,setCounts]=useState([0,0,0]);const [message,setMessage]=useState('');const [error,setError]=useState('');const [incoming,setIncoming]=useState<Backup|null>(null);const [clear,setClear]=useState(false);const [ready,setReady]=useState(false);const file=useRef<HTMLInputElement>(null);
 function refresh(){try{const b=exportBackup();setNickname(b.settings.nickname);setCounts([b.readings.length,b.profiles.length,b.chats.length]);setReady(true);}catch{setError('部分本地数据无法读取，请保留现有数据并检查浏览器存储。');}}
 useEffect(()=>{refresh();},[]);
 function save(e:React.FormEvent){e.preventDefault();try{localStorage.setItem(KEYS.settings,JSON.stringify({nickname:nickname.trim()}));window.dispatchEvent(new Event('yunjian-settings'));setMessage('称呼已保存。');setError('');}catch{setError('保存失败，请检查浏览器存储权限。');}}
 async function readFile(f?:File){if(!f)return;setIncoming(null);setMessage('');setError('');try{if(f.size>8*1024*1024)throw new Error('备份文件不能超过8MB。');const data:unknown=JSON.parse(await f.text());validateBackup(data);setIncoming(data);}catch(e){setError(e instanceof Error?e.message:'备份无法读取。');}finally{if(file.current)file.current.value='';}}
 function restore(){if(!incoming)return;try{restoreBackup(incoming);setIncoming(null);refresh();window.dispatchEvent(new Event('yunjian-settings'));setMessage('备份已恢复，当前浏览器中的云笺数据已替换。');setError('');}catch(e){setError(e instanceof Error?e.message:'恢复失败。');}}
 function clearAll(){try{for(const key of Object.values(KEYS))localStorage.removeItem(key);sessionStorage.removeItem('yunjian.current');setClear(false);setIncoming(null);refresh();window.dispatchEvent(new Event('yunjian-settings'));setMessage('本机云笺数据已清空。');setError('');}catch{setError('未能全部清空，请检查浏览器存储权限。');}}
 return <div className="feature-stack"><section className="panel feature-panel"><div className="section-top"><h2><UserRound size={20}/> 我的云笺</h2><span className="tag">本机资料</span></div><p className="muted feature-intro">这里管理本机资料；登录后可在“账户与云端”手动保存和恢复云端资料。</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success-note">{message}</p>}<form className="feature-form" onSubmit={save}><label>希望云笺如何称呼你<input aria-label="我的称呼" value={nickname} maxLength={30} placeholder="写下你的昵称" onChange={e=>setNickname(e.target.value)}/></label><button className="primary" disabled={!ready}>保存称呼</button></form><div className="stats-grid">{['张提问','份档案','段对话'].map((name,i)=><div key={name}><strong>{counts[i]}</strong><span>{name}</span></div>)}</div></section>
 <section className="panel feature-panel"><h2>把云笺带在身边</h2><p className="muted feature-intro">导出提问、AI解读、档案、聊天和称呼。备份含个人资料，请妥善保管；可在另一台设备导入。</p><div className="button-row"><button className="secondary" onClick={()=>{try{downloadFile('云笺备份-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(exportBackup(),null,2));setMessage('备份已导出。');}catch{setError('导出失败，请检查本地数据。');}}}><Download size={16}/> 导出完整备份</button><button className="secondary" onClick={()=>file.current?.click()}><Upload size={16}/> 导入备份</button><input ref={file} type="file" accept="application/json,.json" className="sr-only" aria-label="选择备份文件" onChange={e=>readFile(e.target.files?.[0])}/></div>{incoming&&<div className="confirm-box"><h3>确认恢复备份</h3><p>{incoming.readings.length} 条提问 · {incoming.profiles.length} 份档案 · {incoming.chats.length} 段对话</p><p>恢复将替换本机当前的云笺数据，建议先导出原有数据。</p><div className="button-row"><button className="primary" onClick={restore}>确认替换并恢复</button><button className="secondary" onClick={()=>setIncoming(null)}>取消恢复</button></div></div>}</section>
 <section className="panel feature-panel"><h2>本地数据管理</h2><p className="muted feature-intro">清空仅影响这个浏览器中的云笺数据。已下载的备份不会被删除。</p>{clear?<div className="confirm-box"><p>确定清空全部本机数据吗？此操作不可撤销。</p><div className="button-row"><button className="primary" onClick={clearAll}>确认清空全部</button><button className="secondary" onClick={()=>setClear(false)}>取消</button></div></div>:<button className="secondary" onClick={()=>setClear(true)}>清空本机云笺数据</button>}</section></div>;
}
